eureka:

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

spring:

  datasource:
    url: ${DB_POSTGRES_URL}
    username: user
    password: password

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: user
    password: password
    virtual-host: gottix

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

rabbitmq:
  exchange:
    main: main
  queue:
    ticket-change: ticket.change
    ticket-comment-change: ticket.comment.change
    ticket-change-notify: ticket.change.notify
  routing-key:
    ticket-change: ticket.change
    ticket-comment-change: ticket.comment.change
    ticket-change-notify: ticket.change.notify

logstash:
  host: ${LOGSTASH_HOST}

security:
  oauth2:
    resourceserver:
      jwt:
        secret-key: VGhpc0lzQURldlNlY3JldEtleVRoYXRNdXN0QmVBdExlYXN0MjU2Qml0c0xvbmdGb3JIUzI1NkFsZ29yaXRobQ==

jwt:
  secret: VGhpc0lzQURldlNlY3JldEtleVRoYXRNdXN0QmVBdExlYXN0MjU2Qml0c0xvbmdGb3JIUzI1NkFsZ29yaXRobQ==
  expiration-ms: 86400000        # 24 h
  refresh-expiration-ms: 604800000  # 7 d

logging:
  level:
    org.springframework.security: DEBUG
