server.port: 8888

spring:

  application:
    name: ConfigServer

  cloud:
    config:
      fail-fast: true

  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false

logging:
  level:
    org.springframework.cloud.config: DEBUG